<?php
// module/Admin/view/admin/admin/index.phtml:

$title = 'Admins';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('admin', ['action' => 'add']) ?>">Add new admin</a>
</p>

<table class="table">
<tr>
    <th>Name</th>
    <th>Position</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($this->paginator as $admin) : ?>
    <tr>
        <td><?= $this->escapeHtml($admin->title) ?></td>
        <td><?= $this->escapeHtml($admin->artist) ?></td>
        <td>
            <a href="<?= $this->url('admin', ['action' => 'edit', 'id' => $admin->id]) ?>">Edit</a>
            <a href="<?= $this->url('admin', ['action' => 'delete', 'id' => $admin->id]) ?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</table>
<?= $this->paginationControl(
    // The paginator object:
    $this->paginator,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'admin']
) ?>